### ISSUE TITLE
[RPi] X dependency

### ISSUE THREAD

**Issue by gyeben** [lunixbochs/glshim#23] opened 2013-12-13 14:08 UTC
If I try to run an OpenGL game with glshim from the console on an RPi, I only get a black screen.
But, if I run the same game with glshim under X, from a terminal emulator, it works perfectly. Why does glshim need X?

**Comment by lunixbochs** [comment] 2015-03-28 21:55
duplicate of #34

**Closed by lunixbochs** 2015-03-28 21:55 UTC
Labels: enhancement
